### ISSUE TITLE
Add absolute minimum docker build to pom.xml

### ISSUE THREAD

**Issue by jypma** [jypma/LB3210#9]
Let's add the absolute minimum to `pom.xml` to be able to build a docker container for this application.

For reference, this is what you'd need with SBT:
```
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.6.1")
```
and then `sbt docker:publishLocal` will do the trick.

To how many lines can we trim down the maven way? :-)

**Comment by jbendsen** [comment]
One way of doing it is adding a Dockerfile to the project:
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]

And then use maven like this:
./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=lb/demo-spring-boot-docker

**Comment by jbendsen** [comment]
I'll research an alternative solution with no Dockerfile.

**Comment by jbendsen** [comment]
I've been looking around and found an alternative using jkube which is the new fabric8 maven plugin. See [jkube site](https://www.eclipse.org/jkube/).

I've found that this will build a docker image and deploy i to kubernetes:
`mvn org.eclipse.jkube:kubernetes-maven-plugin:build org.eclipse.jkube:kubernetes-maven-plugin:resource "-Djkube.enricher.jkube-service.type=NodePort" org.eclipse.jkube:kubernetes-maven-plugin:apply`

No Dockerfile needed. It seems to work on java 8+ (i've tested with java 11). The boot app starts but fails due to lack of database connectivity. I guess the spring boot container has to be on the same network as the database container. 
@jypma, let me know if I should investigate this further.

**Comment by jbendsen** [comment]
I've worked out a new solution that seems to work without a Dockerfile.

Given this command:
`mvn spring-boot:build-image -Dspring-boot.build-image.imageName=logb/demo-project3
`

And this docker-compose.yml file: 
```
version: '3.1'

services:
  app:
    image: logb/demo-project3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/demo
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    ports:
      - 8080:8080
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:13.2-alpine
    # Uncomment this to have the DB come up when you start docker / your laptop:
    #restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: example

    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.8.16-alpine
    # Uncomment this to have the DB come up when you start docker / your laptop:
    #restart: always
    ports:
      - 5672:5672    # AMQP
      - 15672:15672  # Web UI
```

Then 

`docker-compose up -d 
`
will start the spring boot app. 

Is this an acceptable solution?
